### ISSUE TITLE
rifattorizzare Header delle console

### ISSUE THREAD

**Issue by andrealeo83** [openrecordz/openrecordz-web-console#2]
voci di menu:
- home e datasets (lasciare come ora)
- ricerca fulltext
- aggiungi dataset
- profilo con:
   - documentazione
  - esci

vedi data.world

**Comment by stefanodp91** [comment]
manca solo profilo.

- utenti è visibile solo dall'amministratore
- "le mie app" resta dove sta

sitemare il layout dell'header quando si ridimensiona la pagina

**Comment by stefanodp91** [comment]
@andrealeo83 mettendo "documentazione" sotto profilo, significa che solo l'utente loggato può vedere la documentazione?

**Comment by stefanodp91** [comment]
comportamenti anomali se ridotto
