### ISSUE TITLE
aggiungere il campo tags al dataset

### ISSUE THREAD

**Issue by andrealeo83** [openrecordz/openrecordz-web-console#22]
quando crei un nuovo dataset oppure entri in modifica aggiungere il campo testuale tags in cui l'utente può inserire i tag in separati da virgola

**Comment by stefanodp91** [comment]
**_tags**: {tag tag tag tag tag ....}

**Comment by stefanodp91** [comment]
dovrebbe serializzare tutto, valutare presentation

**Comment by stefanodp91** [comment]
replace " " con "#"

**Comment by stefanodp91** [comment]
mettere freccia cliccabile a dx
