### ISSUE TITLE
ricerca fallisce con :

### ISSUE THREAD

**Issue by andrealeo83** [openrecordz/openrecordz-web-console#26]
http://test1.v2.openrecordz.com/datasets#globalSearch/autorizzazioni

**Comment by stefanodp91** [comment]
esempio errore



:
Anno inserimento
:
"2013"
Comune
:
"Malo"
Data e ora inserimento
:
"2013-05-20T15:08:55Z"
Identificatore in OpenStreetMap
:
"2313091048"
Nome
:
"Piscina Comunale"
Provincia
:
"VICENZA"
Regione
:
"Veneto"
id
:
"5a0ddb23e4b0b9e09edc7da6"
_createdby
:
"admin"
_createdon
:
1510857507648
_dataset_ref_id
:
"5a0c82bee4b07b267bf3cf3e"
_latitude
:
"45.6550153"
_location
:
(2) [45.6550153, 11.4015631]
_longitude
:
"11.4015631"
_modifiedby
:
"admin"
_modifiedon
:
1510857507648
_status
:
10
_tenants
:
["test1"]
_type
:
"record"
__proto__
:
Object

**Comment by stefanodp91** [comment]
esempio chiamata che genera l'errore

http://apps.v2.openrecordz.com/datasets#globalSearch/com

**Comment by stefanodp91** [comment]
il record restituito non contiene il dataset
