### ISSUE TITLE
il blog non viene aperto correttamente

### ISSUE THREAD

**Issue by stefanodp91** [openrecordz/openrecordz-web-console#44]
è possibile replicare l'errore accedendo a

http://test1.v2.openrecordz.com/datasets#ds/trasporti-italia --> tab blog

**Comment by stefanodp91** [comment]
viene aperto correttamente su http://XXXX.openrecordz.com/blog/YYYYYYYYY

**Comment by andrealeo83** [comment]
issue duplicata
