### ISSUE TITLE
il blog non funziona (restituisce internal server error)

### ISSUE THREAD

**Issue by andrealeo83** [openrecordz/openrecordz-web-console#52]
puoi verificare

**Comment by nicolan74** [comment]
risolto: aggiunto blog.php (mancava in /mnt/ebsvolume/var/www/openrecordz-web-console-v4)

**Comment by nicolan74** [comment]
risolto: aggiunto blog.php (mancava in /mnt/ebsvolume/var/www/openrecordz-web-console-v4)
