### ISSUE TITLE
aggiungere una livechat di supporto su tutto il sito

### ISSUE THREAD

**Issue by andrealeo83** [openrecordz/openrecordz-web-console#6]
urgente

**Comment by andrealeo83** [comment]
aggiungere chat21 widget come live chat di supporto

**Comment by andrealeo83** [comment]
https://github.com/frontiere21/chat21-web-widget

**Comment by andrealeo83** [comment]
add this prehead.php:




<app-root></app-root>
 


 <script type="text/javascript" src="inline.bundle.js"></script><script type="text/javascript" src="https://chat21-web.firebaseapp.com/polyfills.bundle.js"></script><script type="text/javascript" src="https://chat21-web.firebaseapp.com/scripts.bundle.js"></script><script type="text/javascript" src="https://chat21-web.firebaseapp.com/styles.bundle.js"></script><script type="text/javascript" src="https://chat21-web.firebaseapp.com/vendor.bundle.js"></script><script type="text/javascript" src="https://chat21-web.firebaseapp.com/main.bundle.js"></script>

**Comment by stefanodp91** [comment]
added but disabled for conflicts with js and css

**Comment by stefanodp91** [comment]
set the user and the tenant
